Repository palantir/gradle-external-publish-plugin, pull requests merged in 2021-04, with the labels that each got.

#4 Fix Windows start scripts to have a valid classpath
  changelog/@unreleased/pr-4.v2.yml
  src/main/java/com/palantir/gradle/externalpublish/ExternalPublishApplicationDistPlugin.java
  src/test/groovy/com/palantir/gradle/externalpublish/ExternalPublishRootPluginIntegrationSpec.groovy
Labels: autorelease, merge when ready

#8 Add publishing excavator to list for trying publishing on branches
  src/main/java/com/palantir/gradle/externalpublish/ExternalPublishBasePlugin.java
Labels: no changelog

#11 Remove publishing from feature branches
  src/main/java/com/palantir/gradle/externalpublish/ExternalPublishBasePlugin.java
  src/main/java/com/palantir/gradle/externalpublish/ExternalPublishRootPlugin.java
  src/test/groovy/com/palantir/gradle/externalpublish/ExternalPublishRootPluginIntegrationSpec.groovy
Labels: autorelease, merge when ready, no changelog
